version: '3.8'

services:
  eosio-node:
    container_name: eosio-node
    build: eosio/.
    image: eosio-node
    volumes:
      - ./eosio/data/:/root/eosio/data/
      - ./eosio/config/:/root/eosio/config/
    ports:
      - 8888:8888
    networks:
      - hyperion
    command: nodeos --genesis-json /root/eosio/config/genesis.json --disable-replay-opts --data-dir /root/eosio/data --config-dir /root/eosio/config

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    restart: on-failure
    environment:
      - discovery.type=single-node
      - cluster.name=es-cluster
      - node.name=es01
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - hyperion

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.2
    restart: on-failure
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
    ports:
      - 5601:5601
    networks:
      - hyperion
    depends_on:
      - elasticsearch

  redis:
    container_name: redis
    image: redis:5.0.9-alpine
    restart: on-failure
    networks:
      - hyperion

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.3-management
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_VHOST=/hyperion
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    ports:
      - 15672:15672
    networks:
      - hyperion

  hyperion-indexer:
    container_name: hyperion-indexer
    build: hyperion/.
    image: hyperion
    restart: on-failure
    depends_on:
      - elasticsearch
      - redis
      - rabbitmq
      - eosio-node
    volumes:
      - ./hyperion/config/connections.json:/root/hyperion-history-api/connections.json
      - ./hyperion/config/ecosystem.config.js:/root/hyperion-history-api/ecosystem.config.js
      - ./hyperion/config/chains/:/root/hyperion-history-api/chains/
      - ./scripts/:/root/scripts/
    networks:
      - hyperion
    command: bash -c "/root/scripts/wait-for.sh rabbitmq:15672 && /root/scripts/wait-for.sh elasticsearch:9200 && pm2 start --only eos-indexer --update-env && pm2 logs --raw"

  hyperion-api:
    container_name: hyperion-api
    image: hyperion
    restart: on-failure
    ports:
      - 7000:7000
    depends_on:
      - hyperion-indexer
    volumes:
      - ./hyperion/config/connections.json:/root/hyperion-history-api/connections.json
      - ./hyperion/config/ecosystem.config.js:/root/hyperion-history-api/ecosystem.config.js
      - ./hyperion/config/chains/:/root/hyperion-history-api/chains/
      - ./scripts/:/root/scripts/
    networks:
      - hyperion
    command: bash -c "/root/scripts/wait-for.sh rabbitmq:15672 && /root/scripts/wait-for.sh elasticsearch:9200 && pm2 start --only eos-api --update-env && pm2 logs --raw"

networks:
  hyperion:
    driver: bridge
